[versions]
minecraft = "26.2"

fabric-loader = "0.18.4"

antlr = "4.13.1"
glsl-transformer = "3.0.0-pre3"
jcpp = "1.4.14"

fabric-api = "0.153.0+26.2"

sodium = "mc26.2-0.9.0-fabric"
iris = "1.11.1+26.2-fabric"

[libraries]
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

antlr4-runtime = { module = "org.antlr:antlr4-runtime", version.ref = "antlr" }
glsl-transformer = { module = "io.github.douira:glsl-transformer", version.ref = "glsl-transformer" }
jcpp = { module = "org.anarres:jcpp", version.ref = "jcpp" }

sodium = { module = "maven.modrinth:sodium", version.ref = "sodium" }
iris = { module = "maven.modrinth:iris", version.ref = "iris" }